const DICT = {
  id: {
    greeting_morning: 'Selamat pagi', greeting_afternoon: 'Selamat siang', greeting_evening: 'Selamat sore',
    online: 'Online', offline: 'Offline', busy: 'Sedang trip',
    earnings_today: 'Pendapatan hari ini', trips_today: 'Trip', online_hours: 'Jam online',
    acceptance: 'Penerimaan', rating: 'Rating',
    mode_ride: 'Ride', mode_rental: 'Sewa Harian', mode_airport: 'Antar Jemput',
    go_online: 'Mulai cari order', go_offline: 'Berhenti',
    incoming: 'Order masuk', accept: 'Terima', reject: 'Lewati',
    pickup: 'Jemput di', dropoff: 'Antar ke', distance: 'Jarak', duration: 'Estimasi',
    fare: 'Estimasi tarif', surge_active: 'Tarif Surge aktif',
    navigate: 'Navigasi', call: 'Telepon', message: 'Pesan',
    arrived: 'Sudah sampai', start_trip: 'Mulai Trip', end_trip: 'Selesaikan Trip',
    trip_complete: 'Trip selesai', total: 'Total', base_fare: 'Tarif dasar',
    surge: 'Bonus surge', tips: 'Tip', rate_rider: 'Rating penumpang',
    riwayat: 'Riwayat', earnings: 'Pendapatan', profile: 'Profil', home: 'Beranda',
    today: 'Hari ini', week: 'Minggu ini', month: 'Bulan ini',
    target: 'Target', achieved: 'Tercapai',
    looking_for_orders: 'Mencari order…', upcoming: 'Order terjadwal',
    nearby_demand: 'Permintaan sekitar', high: 'Tinggi', medium: 'Sedang', low: 'Rendah',
    minutes_short: 'mnt', km_short: 'km', away: 'jauh',
    passenger: 'Penumpang', car: 'BYD M6 Standard', plate: 'B 2845 EVS',
    new_order: 'Order Baru', you_earn: 'Kamu dapat', detail: 'Detail',
    seva_partner: 'SEVA Partner', completed: 'Selesai', cancelled: 'Dibatalkan',
    see_all: 'Lihat semua', weekly_target: 'Target mingguan',
    simulate_order: 'Simulasi Order Masuk', seconds: 'detik',
  },
  en: {
    greeting_morning: 'Good morning', greeting_afternoon: 'Good afternoon', greeting_evening: 'Good evening',
    online: 'Online', offline: 'Offline', busy: 'On trip',
    earnings_today: "Today's earnings", trips_today: 'Trips', online_hours: 'Online hrs',
    acceptance: 'Acceptance', rating: 'Rating',
    mode_ride: 'Ride', mode_rental: 'Daily Rental', mode_airport: 'Airport',
    go_online: 'Go online', go_offline: 'Go offline',
    incoming: 'Incoming order', accept: 'Accept', reject: 'Skip',
    pickup: 'Pick up at', dropoff: 'Drop off at', distance: 'Distance', duration: 'ETA',
    fare: 'Est. fare', surge_active: 'Surge fare active',
    navigate: 'Navigate', call: 'Call', message: 'Chat',
    arrived: 'Arrived', start_trip: 'Start trip', end_trip: 'End trip',
    trip_complete: 'Trip complete', total: 'Total', base_fare: 'Base fare',
    surge: 'Surge bonus', tips: 'Tip', rate_rider: 'Rate rider',
    riwayat: 'History', earnings: 'Earnings', profile: 'Profile', home: 'Home',
    today: 'Today', week: 'This week', month: 'This month',
    target: 'Target', achieved: 'Achieved',
    looking_for_orders: 'Looking for orders…', upcoming: 'Scheduled',
    nearby_demand: 'Demand nearby', high: 'High', medium: 'Medium', low: 'Low',
    minutes_short: 'min', km_short: 'km', away: 'away',
    passenger: 'Rider', car: 'BYD M6 Standard', plate: 'B 2845 EVS',
    new_order: 'New order', you_earn: "You'll earn", detail: 'Detail',
    seva_partner: 'SEVA Partner', completed: 'Completed', cancelled: 'Cancelled',
    see_all: 'See all', weekly_target: 'Weekly target',
    simulate_order: 'Simulate Incoming Order', seconds: 'sec',
  },
};

export const T = (lang = 'id') => DICT[lang] || DICT.id;

export const Rp = (n) => 'Rp ' + n.toLocaleString('id-ID');
